### ISSUE TITLE
Re-writing using modern tech

### ISSUE THREAD

**Issue by mr-islam** [mr-islam/al-kitab#59]
The current code is working, but perhaps I should move it to React? (I learned React after making this app)

I'm tempted, but the app works just fine – it would just be behind the scenes work so I feel cool or have fun.

**Comment by mr-islam** [comment]
Pros:
- Better, stable base to build new features on
- Easier for others to contribute
- Chance to practice more React and maybe try Redux
- Fun to do

Cons:
- Takes away dev time from new features

**Comment by mr-islam** [comment]
I'm feeling a real urge to write it in Svelte, since:

- Others haven't contributed to a relatively clear and simple plain-JS codebase either, so I shouldn't worry about them
- Svelte has excited me for a long time and I've wanted to try it out – it will motivate me
- The concepts I'll learn will solidify my overall skills, and my React will improve too
- I really won't be working on new features until fixing up existing things – I want to start over with a v4. Each time I've bumped a version the app has gotten 10x better, let's do it again.

I've got a boat load of issues, and it'll be better to do a fresh write instead of updating this.

Bismillah, I'll do this in svelte insha Allah. Right after I get on with the Quran Summaries apps (private repos for now)

**Comment by waelio** [comment]
Why react?? I suggest a more complete framework like Vue. I'll give you a hand if you need to.
Currently I am working on few implementation in Python, PHP & NodeJS as backends. I have an obsolete VanillaJS and a fresh VueJS. Once you go Vue you'll detch react

**Comment by mr-islam** [comment]
Oh yes Vue is really interesting and I would love to try it out in depth and work with it. Thank you for your kind offer 😊

But my main preference from React is because 1. I have experience with it already, and 2. it's more likely to be helpful experience for a job in the future (hopefully!), since it's more popular. Vue is growing fast though so that might change soon!

**Comment by waelio** [comment]
I hear you! But the truth is that the market is stupid and backward minded, and to prove it, the biggest demand right now is for Angular then React. It's the hype. Google vs Facebook, who has the the bigger @#$%. Sounds silly and unleasistic? true. So I figured, if I learn vue thoroughly, it will prepare me for react. Matter of fact, the two are so similar once you learn one you'll easily catch up with the other, so the idea is to start with the straightforward one before you start dealing with the shortcomings of the others.
I can help you with react as well if that is what you really want, but it is not what I would suggest at first.

**Comment by mr-islam** [comment]
Never done a codebase migration… would starting from scratch be easier, or migrating component by component?

I think it's a simple app with limited and related functionality; starting from scratch shouldn't be hard and will be better in the long run

**Comment by ultrasamad** [comment]
@mr-islam Salaam, I think when it comes to framework or library choice, the decision lies with you the original/fulltime maintainer and it should be something you are more comfortable with. No matter the framework you choose, there will be people available to contribute.

**Comment by mr-islam** [comment]
@ultrasamad Wa alaykum as salam, thank you!

Looking forward to make some progress next month, insha Allah, after my semester is over

**Comment by mr-islam** [comment]
Work is underway using Svelte! Thank you to everyone who replied here and expressed interest about the project

You can follow the new repo and development here:

https://github.com/mr-islam/qawl-svelte

**Comment by mr-islam** [comment]
The re-write is going *amazingly* alhamdulillah, and I have just been through all the old issues here and added them to the new dev plan. 

After the re-write is released, I will publish a final update to this app, where it prompts users to install the new one manually (I don't think auto-update can handle two different codebases like this). 

Then, this repo can be archived.
